all:
  children:
    routers:
      hosts:
        RR1:
          ansible_host: 192.168.1.2
          ansible_connection: network_cli
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        RR2:
          ansible_host: 192.168.1.3
          ansible_connection: network_cli
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    switches:
      hosts:
        SR1:
          ansible_host: 192.168.0.3
          ansible_connection: network_cli
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        SR2:
          ansible_host: 192.168.1.10
          ansible_connection: network_cli
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        SR3:
          ansible_host: 192.168.1.11
          ansible_connection: network_cli
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        SG3:
          ansible_host: 192.168.1.12
          ansible_connection: network_cli
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars:
    ansible_user: cisco
    ansible_password: cisco
    ansible_network_os: ios
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

    
